# Generated by Django 4.2.3 on 2023-07-18 15:52

import common.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Фвмилия')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=common.utils.generate_filename, verbose_name='Фото')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оклад')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='department.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Cотрудник',
                'verbose_name_plural': 'Cотрудники',
            },
        ),
    ]
